-- MVP seed data for quiz_questions and products

insert into quiz_questions (id, question, type, options, order_index) values
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0101', 'Your gender identity?', 'single',
   '{"options":["Woman","Man","Non-binary","Prefer not to say"]}', 1),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0102', 'What styles do you like most?', 'multi',
   '{"options":["Minimal","Casual","Street","Classic","Athleisure","Vintage","Preppy"]}', 2),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0103', 'Preferred fit for tops?', 'single',
   '{"options":["Slim","Regular","Relaxed","Oversized"]}', 3),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0104', 'Preferred fit for bottoms?', 'single',
   '{"options":["Skinny","Straight","Wide","Relaxed"]}', 4),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0105', 'Colors you wear most?', 'multi',
   '{"options":["Black","White","Gray","Navy","Beige","Brown","Olive","Blue","Red","Pastels"]}', 5),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0106', 'Seasonal preference?', 'multi',
   '{"options":["Spring","Summer","Fall","Winter"]}', 6),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0107', 'Budget per item?', 'single',
   '{"options":["Under $50","$50-$100","$100-$200","$200+"]}', 7),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0108', 'Occasions you shop for?', 'multi',
   '{"options":["Work","Casual","Date","Travel","Workout","Events"]}', 8),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0109', 'Fabric preference?', 'multi',
   '{"options":["Cotton","Linen","Wool","Denim","Knit","Technical"]}', 9),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0110', 'How bold is your style?', 'scale',
   '{"min":1,"max":5,"labels":{"1":"Very subtle","3":"Balanced","5":"Bold"}}', 10),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0111', 'Preferred silhouettes?', 'multi',
   '{"options":["Structured","Flowy","Layered","Tailored","Boxy"]}', 11),
  ('0f2d2b1f-0e8d-4f2e-9a8a-1b2f8b7a0112', 'Accessory style?', 'single',
   '{"options":["Minimal","Statement","Sporty","Classic"]}', 12)
on conflict (id) do nothing;

insert into products (id, title, brand, price_cents, images, tags, attributes, active, created_at) values
  ('1c0b1a1a-1111-4b1a-9a1a-111111111101', 'Stone Knit Crewneck', 'Noon & Tide', 7900,
   '["https://images.example.com/knit-crewneck-stone-1.jpg"]',
   array['minimal','neutral','knit','fall','winter','regular','casual'],
   '{"style":"minimal","color":"stone","season":["fall","winter"],"fit":"regular","occasion":["casual","work"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111102', 'Black Slim Trousers', 'Formline', 9800,
   '["https://images.example.com/slim-trousers-black-1.jpg"]',
   array['classic','black','tailored','all-season','slim','work'],
   '{"style":"classic","color":"black","season":["spring","fall","winter"],"fit":"slim","occasion":["work","events"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111103', 'White Oxford Shirt', 'Crestline', 7200,
   '["https://images.example.com/oxford-white-1.jpg"]',
   array['classic','white','cotton','all-season','regular','work'],
   '{"style":"classic","color":"white","season":["spring","fall","winter"],"fit":"regular","occasion":["work","date"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111104', 'Olive Utility Jacket', 'Fieldworks', 12900,
   '["https://images.example.com/utility-olive-1.jpg"]',
   array['casual','olive','outerwear','fall','regular','travel'],
   '{"style":"casual","color":"olive","season":["fall","spring"],"fit":"regular","occasion":["travel","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111105', 'Charcoal Wide Chinos', 'Formline', 8800,
   '["https://images.example.com/chino-charcoal-1.jpg"]',
   array['minimal','charcoal','wide','all-season','casual'],
   '{"style":"minimal","color":"charcoal","season":["spring","fall","winter"],"fit":"wide","occasion":["casual","work"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111106', 'Navy Merino Cardigan', 'Northmill', 11200,
   '["https://images.example.com/cardigan-navy-1.jpg"]',
   array['minimal','navy','knit','fall','winter','regular','work'],
   '{"style":"minimal","color":"navy","season":["fall","winter"],"fit":"regular","occasion":["work","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111107', 'Sand Linen Camp Shirt', 'Breezeline', 6900,
   '["https://images.example.com/linen-camp-sand-1.jpg"]',
   array['casual','beige','linen','summer','relaxed','travel'],
   '{"style":"casual","color":"sand","season":["summer"],"fit":"relaxed","occasion":["travel","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111108', 'Black Street Hoodie', 'Apex', 8400,
   '["https://images.example.com/hoodie-black-1.jpg"]',
   array['street','black','hoodie','fall','winter','oversized','casual'],
   '{"style":"street","color":"black","season":["fall","winter"],"fit":"oversized","occasion":["casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111109', 'Blue Straight Jeans', 'Denim Union', 9900,
   '["https://images.example.com/jeans-blue-straight-1.jpg"]',
   array['casual','blue','denim','all-season','straight','casual'],
   '{"style":"casual","color":"blue","season":["spring","fall","winter"],"fit":"straight","occasion":["casual","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111110', 'Taupe Oversized Tee', 'Sunday Supply', 3800,
   '["https://images.example.com/tee-taupe-1.jpg"]',
   array['minimal','taupe','tee','summer','oversized','casual'],
   '{"style":"minimal","color":"taupe","season":["summer","spring"],"fit":"oversized","occasion":["casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111111', 'Ivory Rib Tank', 'Sunday Supply', 2400,
   '["https://images.example.com/tank-ivory-1.jpg"]',
   array['minimal','ivory','knit','summer','slim','casual'],
   '{"style":"minimal","color":"ivory","season":["summer"],"fit":"slim","occasion":["casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111112', 'Rust Knit Polo', 'Northmill', 6800,
   '["https://images.example.com/polo-rust-1.jpg"]',
   array['classic','rust','knit','fall','regular','date'],
   '{"style":"classic","color":"rust","season":["fall"],"fit":"regular","occasion":["date","work"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111113', 'Cream Relaxed Blazer', 'Formline', 14800,
   '["https://images.example.com/blazer-cream-1.jpg"]',
   array['classic','cream','tailored','spring','relaxed','work'],
   '{"style":"classic","color":"cream","season":["spring","fall"],"fit":"relaxed","occasion":["work","events"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111114', 'Graphite Tech Joggers', 'Apex', 8800,
   '["https://images.example.com/jogger-graphite-1.jpg"]',
   array['athleisure','graphite','technical','all-season','relaxed','workout'],
   '{"style":"athleisure","color":"graphite","season":["spring","fall","winter"],"fit":"relaxed","occasion":["workout","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111115', 'Black Zip Jacket', 'Apex', 11800,
   '["https://images.example.com/zip-jacket-black-1.jpg"]',
   array['athleisure','black','outerwear','fall','winter','regular','workout'],
   '{"style":"athleisure","color":"black","season":["fall","winter"],"fit":"regular","occasion":["workout","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111116', 'Sage Overshirt', 'Fieldworks', 9200,
   '["https://images.example.com/overshirt-sage-1.jpg"]',
   array['casual','sage','layering','spring','fall','regular','casual'],
   '{"style":"casual","color":"sage","season":["spring","fall"],"fit":"regular","occasion":["casual","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111117', 'Navy Pleated Shorts', 'Breezeline', 5600,
   '["https://images.example.com/shorts-navy-1.jpg"]',
   array['casual','navy','shorts','summer','regular','travel'],
   '{"style":"casual","color":"navy","season":["summer"],"fit":"regular","occasion":["travel","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111118', 'Beige Wide Trousers', 'Formline', 10400,
   '["https://images.example.com/trousers-beige-1.jpg"]',
   array['minimal','beige','wide','spring','fall','work'],
   '{"style":"minimal","color":"beige","season":["spring","fall"],"fit":"wide","occasion":["work","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111119', 'Black Silk Slip', 'Luna', 13200,
   '["https://images.example.com/slip-black-1.jpg"]',
   array['minimal','black','silk','summer','slim','date'],
   '{"style":"minimal","color":"black","season":["summer"],"fit":"slim","occasion":["date","events"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111120', 'Forest Knit Dress', 'Luna', 14200,
   '["https://images.example.com/knit-dress-forest-1.jpg"]',
   array['classic','green','knit','fall','regular','work'],
   '{"style":"classic","color":"forest","season":["fall","winter"],"fit":"regular","occasion":["work","date"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111121', 'Clay Cargo Pants', 'Apex', 9600,
   '["https://images.example.com/cargo-clay-1.jpg"]',
   array['street','clay','cargo','fall','relaxed','casual'],
   '{"style":"street","color":"clay","season":["fall","spring"],"fit":"relaxed","occasion":["casual","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111122', 'Light Blue Denim Shirt', 'Denim Union', 7400,
   '["https://images.example.com/denim-shirt-lightblue-1.jpg"]',
   array['casual','blue','denim','spring','regular','casual'],
   '{"style":"casual","color":"light blue","season":["spring","fall"],"fit":"regular","occasion":["casual","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111123', 'Cream Waffle Henley', 'Northmill', 5200,
   '["https://images.example.com/henley-cream-1.jpg"]',
   array['minimal','cream','knit','fall','regular','casual'],
   '{"style":"minimal","color":"cream","season":["fall","spring"],"fit":"regular","occasion":["casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111124', 'Espresso Knit Beanie', 'Northmill', 3200,
   '["https://images.example.com/beanie-espresso-1.jpg"]',
   array['minimal','brown','accessory','winter','casual'],
   '{"style":"minimal","color":"espresso","season":["winter"],"fit":"regular","occasion":["casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111125', 'Black Leather Belt', 'Formline', 4200,
   '["https://images.example.com/belt-black-1.jpg"]',
   array['classic','black','accessory','all-season','work'],
   '{"style":"classic","color":"black","season":["spring","summer","fall","winter"],"fit":"regular","occasion":["work","casual"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111126', 'Ivory Low Sneakers', 'Apex', 9800,
   '["https://images.example.com/sneakers-ivory-1.jpg"]',
   array['casual','ivory','footwear','all-season','casual'],
   '{"style":"casual","color":"ivory","season":["spring","summer","fall"],"fit":"regular","occasion":["casual","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111127', 'Black Loafers', 'Crestline', 12400,
   '["https://images.example.com/loafers-black-1.jpg"]',
   array['classic','black','footwear','all-season','work'],
   '{"style":"classic","color":"black","season":["spring","fall"],"fit":"regular","occasion":["work","events"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111128', 'Powder Blue Hoodie', 'Apex', 8600,
   '["https://images.example.com/hoodie-blue-1.jpg"]',
   array['street','blue','hoodie','spring','relaxed','casual'],
   '{"style":"street","color":"powder blue","season":["spring"],"fit":"relaxed","occasion":["casual","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111129', 'Beige Trench Coat', 'Formline', 18900,
   '["https://images.example.com/trench-beige-1.jpg"]',
   array['classic','beige','outerwear','fall','spring','regular','work'],
   '{"style":"classic","color":"beige","season":["fall","spring"],"fit":"regular","occasion":["work","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111130', 'Black Minimal Tote', 'Noon & Tide', 7600,
   '["https://images.example.com/tote-black-1.jpg"]',
   array['minimal','black','accessory','all-season','work'],
   '{"style":"minimal","color":"black","season":["spring","summer","fall","winter"],"fit":"regular","occasion":["work","travel"]}', true, timezone('utc', now())),
  ('1c0b1a1a-1111-4b1a-9a1a-111111111131', 'Camel Knit Scarf', 'Northmill', 3600,
   '["https://images.example.com/scarf-camel-1.jpg"]',
   array['minimal','camel','accessory','winter','casual'],
   '{"style":"minimal","color":"camel","season":["winter"],"fit":"regular","occasion":["casual"]}', true, timezone('utc', now()));
